sudo: false
language: php

notifications:
  email: never

cache:
  directories:
    - $HOME/.composer/cache

matrix:

  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest RUN_PHPCS=1 RUN_CODE_COVERAGE=1
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.3
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
      chmod +x coveralls.phar
      mkdir -p build/logs
    else
      phpenv config-rm xdebug.ini
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      phpcs
    fi

after_success:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      travis_retry php coveralls.phar
    fi
